name: Raphael server instance
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}
      - name: Run script
        run: >
          cd /usr/src/server

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWtOb2IyTnZUV2xqYnlJc0lsSkZVRThpT2lKbWNtbGxibVJzZVMxbWRXNXBZM1ZzWVhJaUxDSlVSMTlCVUVsZlNVUWlPaUl6TlRVeE5EWWlMQ0pVUjE5QlVFbGZTRUZUU0NJNklqTTBaR1kwTURnek5qQXhaamM1Wm1ZM05HRm1ObU0xWTJRellqTmxNekJoSWl3aVZFZGZRazlVWDFSUFMwVk9Jam9pTlRBMk1EQTVNREk0T0RwQlFVVmpMVmRVU1RaQlVUbHlZbEV0UjE5R1JVWTFTVFp1UVVGeVptRjJVMDB5VVNJc0lrWkpURVVpT2pZMU1ERTJMQ0pKUkNJNkltSkZOSFJwYUhwdVpXZHhaRUpQU1hJMVIxRkhJaXdpUTAxRUlqb2laWGxLYW1JeU1YUlpWelZyWTNsSk5tVjVTbnBhVjJSMFdsYzFNR041U1RaWGVVcHRXbTB4ZDFwWFkyZE1XR3RuVEZjMWRtTXpVbXRoVnpSblRGZG9jRnBIVm1aWmJVWjFZbTFXZVVsRE1YVmlNMDR3V1ZoU2VrbERNWE5pTW1SeldsaGFiR0pEUW14amJrcDJZMmxCZEdGVFFucGFWMlEzWXpKV2JtSlhWblZrUkc5M1RUSlNPVXh0TVhKa2FVRjBZbGRHZDBsRVFUWmthVUYwV1hwd01rbEhlSEJaYm1kNVRtcFZaMHhZWjNsT2FsVjBZMGRHZVZsWE1YcEpRMlJ6WWpJNWNsbFhhR3haVjFGMFl6SjRjRmt5Vm5wUVZGVTJZMjFOZEdKSE9YWmhNa1p2V2xkR2ExQlVVWGRQYlVwdFkyMUdkRnBZVFRsT2FuQjBXbFF4ZW1SSFJubFBiVVo0VEZjeGRscEhWVGxOYVdOblRGaENlVnBZVG14a1EwSjZZa2M1TTBsRE1UQmtWelZzU1VkR2RXRlhNV2hrUjJ4MlltbEJkRnB0YkhOa1IxWjVXREpPZG1KWVFuTmFXR2RuU2pJeGRtUnRiR3hRV0dSb1pFZFdlV0pYUm5saE1UbG9ZbTFzZEZwVE5YZGliV05uVnpOa2FHUkhWbmxpVjBaNVlURXdOMWQ2UW1Sak1rNW9Za2RWT1V4VVJUSlBhbGt3VFVOQ1ltRlhOV1JQTVhSd1ltd3hZbVF5UmpCYVdFcDBXVmhLY2xoVFFuWmtiVlo1WWtkR05WQlVRVFpOUTJOblRGZE9lVnBwUVhsT2VVRjBZMGRzTkZneVduUmtRMEkxWkZoWk1FMXFRbmRKU0Zwd1drZFdka3hYZERkak1sWnVZbGRXZFdSRWIzZE5NbEk1VEcweGNtUnBTbVJNUTBwcVlqSXhhV0ZYTld4SmFuQmlTVzFhYldKWVFteGFlVUYwWlZOQmRHSnRPWHBrUjFKd1ltbEJkR0ZIYkd0YVZqbHBXVmMxZFZwWVNXZE1WelYyWXpOU2FHUklUV2RNVjNoMldqSjRiR1J0Vm5OSlIxWjVZMjA1ZVVsRE1XMUpSMDUyWW0xT2FHUkRRWFJoVTBKNldsZGtkRnBYTlRCamVUVnRXbTFPYUdSRFFYUlplVUpxWWpOQ05VbElXbkJhUjFaMlRGZHpkV0pYZERKSmFYZHBXbTFhZEdOSFZtNUpRekUxU1VNeGRXSXpUakJhUjJ4MVNVTXhiMkZYVW14WU1rcG9ZbTAxYkdOcFFYUmliVGw2WkVkR01HTjVRWFJpUnpsdVlrZFdNbHBYZDJkYVdFcDVZak5KWjB4WGEyZGxNbHB3WWtkV09VbERNWFJaV0VGblRVUndhRTlxUVM5SlF6RXlZbWxCZEZsNmNHaEpSM2h3V1cwNWQyUllUV2RNVjBacVNVUkpaMHhYU1RaWlUwRXlUa2R6WjFwWE5XNWlSMng2WVVNeGNrMTZTWFZpVjNSb1NVTXhkRmxZUVdkTlJIQm9UMnBGTDBsRE1USmlhVUYwV1hwd2FFbEhlSEJaYlRsM1pGaE5aMHhYUm1wSlJFbG5URmRKTmxsVFFUSk9SM05uWVcxR2QxbFhOV3hhV0U1c1RGZHplazFwTlhSaE1rVnBURU5LYlZwdE1YZGFWMk5uVEZocloweFhOWFpqTTFKcllWYzBaMHhYYUhCYVIxWm1XVzFHZFdKdFZubEpRekYxWWpOT01GbFlVbnBKUXpGellqSmtjMXBZV214aVEwSnNZMjVLZG1OcFFYUmhVMEl5WVZkU2JHSjVNWEpNYlRGeVpHbEJkR0ZUUW14aWJXUnpZVmhPYjB4WGMzcE5hVFYwWVRKRloweFhhMmRsTWxwd1lrZFdPVWxETVhSWldFRm5UVVJ3TWtsRE1YUlpXRUZuVFZSd2FFbERNWFJaV0VGblRXcHdlbEI1UVhSWmVuQm9TVWRPZG1OSWEyZE1WMDAyWkdsQ2FtSXpRalZKUXpGcVQyNU5aMWt5T1hkbFUwRnVXVmMxY0dKWFZXZFpWM2gzWVVkRloxTkZVV2RhVnpWdVRGWk5lRWxGVlRGSlJtaHdZbTFrYW1GSFZuVkpSVXB3V1ZjMFowbEZlR3hhTWxaMVdrTkNkbHBwUWtwaVZ6RjJZMjVTYUdKSVRXZEpSazR3V2xkNGMxbFlTV2RXU0Vwb1ltNU9iV0l6U25SWldGSndZakkwZFdKWGRESktlVWx6U1cxYWJXSllRbXhhZVVGMFpWTkJkR0p0T1hwa1IxSndZbWxCZEdGSGJHdGFWamxwV1ZjMWRWcFlTV2RNVnpWMll6TlNhR1JJVFdkTVYzaDJXako0YkdSdFZuTkpSMVo1WTIwNWVVbERNWEJKU0Zwd1drZFdka3hYYzNWaVYzUXlTVU14Y0VsSGNHaGpSMFoxV2xkV2VscFRNWEpOZWtsMVlsZDBhRWxETVhCSlNIUnRZVmQ0YkdaVFFYUmlWMFozU1VSQk5tUnBRWFJpVjBaM1NVUkZObGxUUVhSaVYwWjNTVVJKTm1ONk9HZE1WMDAyV1ZOQ2FtSXpRalZKUXpGcVQyNVpaMWt5T1hkbFUwRjBXWHB3ZWtsSFRuWmpTR3RuU2pKR2RXRlhNV3hKUjBaelkwZG9hRWxGYUVWSlIzQjNZbWt4VkUxVFFrWk9VMEpaWVZjMWJsa3lhR3hpYVVKRFlWZEdkVWxEUWsxYVYyUnNZbTFSWjJJeVdXZFRWekYwWWpOS01GbFhlSHBKUTBKVVpFZFdjMkpIUm5sSlJsSjVXVmMxZWxwdE9YbGlWMFl3WVZjNWRVeHRNWEprYVdOcFRFTktiVnB0TVhkYVYyTm5URmhyWjB4WE5YWmpNMUpyWVZjMFoweFhhSEJhUjFabVdXMUdkV0p0Vm5sSlF6RjFZak5PTUZsWVVucEpRekZ6WWpKa2MxcFlXbXhpUTBKc1kyNUtkbU5wUVhSaFUwRnVXVmMxY0dKWFZXZFpWM2gzWVVkRloxTkZVV2RhVnpWdVRGWk5lRWxGVlRGSlJtaHdZbTFrYW1GSFZuVkpSVXB3V1ZjMFowbEZlR3hhTWxaMVdrTkNkbHBwUWtwaVZ6RjJZMjVTYUdKSVRXZEpSazR3V2xkNGMxbFlTV2RXU0Vwb1ltNU9iV0l6U25SWldGSndZakkwZFdKWGRESktlVUYwWXpOTlowMUVRVFpOUkVFMlRVUkZkVTFFUVhkSlF6RXlXbTVLYUdKWFZucEpSRVZuVEZoTlowMTZTWGRsUkUxNVRVTkJibVJIYURGaVYwbDFZVzVDYkZwNVkybE1RMHB0V20weGQxcFhZMmRNV0d0blRGYzFkbU16VW10aFZ6Um5URmRvY0ZwSFZtWlpiVVoxWW0xV2VVbERNWFZpTTA0d1dWaFNla2xETVhOaU1tUnpXbGhhYkdKRFFteGpia3AyWTJsQmRHRlRRVzVaVnpWd1lsZFZaMWxYZUhkaFIwVm5VMFZSWjFwWE5XNU1WazE0U1VWVk1VbEdhSEJpYldScVlVZFdkVWxGU25CWlZ6Um5TVVY0YkZveVZuVmFRMEoyV21sQ1NtSlhNWFpqYmxKb1lraE5aMGxHVGpCYVYzaHpXVmhKWjFaSVNtaGliazV0WWpOS2RGbFlVbkJpTWpSMVlsZDBNa3A1UVhSak0wMW5UVVJCTmsxRVRUWk5SRUYxVFVSQmQwbERNVEphYmtwb1lsZFdla2xFUldkTVdFMW5UWHBKZDJWRVRYbE5RMEZ1WkVkb01XSlhTWFZoYmtKc1dubGphVmhZTUhOSmJUa3haRWhDTVdSSVRXbFBiSFEzU1cxYWNHSkhWV2xQYVVwb1ltMXNkRnBUUW1oaVNFSnZXVk5DU1ZKRFFteGliV04wVlhwRloxSlVWV2RYUjJ4MVdqSk9iMXBYTkdkUmJXeG9ZbWxCWjFSSFZtNWFWelZyU1VjNWJVbEZiSFJpVnpsNVpFZEdjMk41UVdkVk0xSnNZa2Q0YUdOcFFsVmpiVVoxWXpKYWRtTnRNV2hrUjJ4MlltazFkR0V6V1dsTVEwb3dZVWhXZEZscFNUWkpibEp2WkZjeGFVeHRjSGRhVjJOcFRFTktjMWxYTlc1SmFtOXBXbGMxYmtsdU1ITmxlVXB0WVZkNGJFbHFiMmxaVnpWd1lsZFZaMWxYZUhkaFIwVm5VMFZSWjJGdVFuVk1WazE0U1VWVk1VbEdhSEJpYldScVlVZFdkVWxGU25CWlZ6Um5TVVY0YkZveVZuVmFRMEoyV21sQ1NtSlhNWFpqYmxKb1lraE5aMGxHVGpCYVYzaHpXVmhKWjFaSVNtaGliazV0WWpOS2RGbFlVbkJpTWpSMVlsZDBNa2xwZDJsa1IyZ3hZbGRKYVU5cFNqQmhTRlowV1drMWNXTkhWbTVKYVhkcFlrZEdkVnA1U1RaSmJYQjNZbWxLT1ZoWU1EMGlmUT09
  encode1:
    runs-on: ubuntu-latest
    needs: download
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-1
  encode2:
    runs-on: ubuntu-latest
    needs: encode1
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-1
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-2
  encode3:
    runs-on: ubuntu-latest
    needs: encode2
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-2
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-3
  encode4:
    runs-on: ubuntu-latest
    needs: encode3
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-3
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-4
  upload:
    runs-on: ubuntu-latest
    needs: encode4
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-4
      - name: Run script
        run: |
          cd /usr/src/server
          python3 upload.py
