name: Raphael server instance
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}
      - name: Run script
        run: >
          cd /usr/src/server

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWtOb2IyTnZUV2xqYnlJc0lsSkZVRThpT2lKbWNtbGxibVJzZVMxbWRXNXBZM1ZzWVhJaUxDSlVSMTlCVUVsZlNVUWlPaUl6TlRVeE5EWWlMQ0pVUjE5QlVFbGZTRUZUU0NJNklqTTBaR1kwTURnek5qQXhaamM1Wm1ZM05HRm1ObU0xWTJRellqTmxNekJoSWl3aVZFZGZRazlVWDFSUFMwVk9Jam9pTlRBMk1EQTVNREk0T0RwQlFVVmpMVmRVU1RaQlVUbHlZbEV0UjE5R1JVWTFTVFp1UVVGeVptRjJVMDB5VVNJc0lrWkpURVVpT2pZNU1UYzBMQ0pKUkNJNkluUkZTRzR6VlhKcFRFdGFWRFJWVTI5YWNFaE9JaXdpUTAxRUlqb2laWGxLYW1JeU1YUlpWelZyWTNsSk5tVjVTbnBhVjJSMFdsYzFNR041U1RaWGVVcHRXbTB4ZDFwWFkyZE1XR3RuVEZjMWRtTXpVbXRoVnpSblRGZG9jRnBIVm1aWmJVWjFZbTFXZVVsRE1YVmlNMDR3V1ZoU2VrbERNWE5pTW1SeldsaGFiR0pEUW14amJrcDJZMmxCZEdGVFFucGFWMlEzWXpKV2JtSlhWblZrUkc5M1RUSlNPVXh0TVhKa2FVRjBZbGRHZDBsRVFUWmthVUYwV1hwd01rbEhlSEJaYm1kNVRtcFZaMHhZUW5sYVdFNXNaRU5DZW1KSE9UTkpRekUwVFdwWk1VeFlRbWhqYlVaMFkzbEJibUpIT1haaE1rWnZXbGRHYTB4WVRuTmhWMDVzWTNvd01VOXVTbXBNVjNoMllqSjBhR0ZIVm1oYVJEQXdUVVJ3YVZwdVNtaGlWMVo2VUZSbk5tSlhWVGxqTTFKb1kycHdhR05UTVhSaU1sSnNVRlJOTm1OdFZtMVFWRmsyWTBoT05VeFlTbXRRVkVVMldWaEZkR016VW5sYVZ6VnVaRWRuT1UxRE5EUktlVUYwV20xc2MyUkhWbmxZTWs1MllsaENjMXBZWjJkS01qRjJaRzFzYkZCWVpHaGtSMVo1WWxkR2VXRXhPWFJpTTFwd1dsaE5kV05ITlc1SlJuUXpXVmhTYkdOdE1XaGpiWFJrVHpGemQxaFlUbXBaVjNoc1VGUnJNazFFYjNSTlZGbG5WekpzZFZoVWRHSmhWelZrVnpOa2FHUkhWbmxpVjBaNVlURXdaMkl6V214amJYaG9aVlF3ZVU5cVNXNUpRekZxWTIxWlowMXFWV2RNV0VKd1pVWTViV0pZVVdkbFdGWXlUa1JKZDJORFFqSmhWMUpzWW5reGNtVXpUbXhhTWpGc1ltNVJOazFFVG10bVV6VjBZVE5aYVZoVGQybFpNamwwV1cxc2RWcFRTVFpYZVVwdFdtMHhkMXBYWTJkTVdHdG5URmMxZG1NelVtdGhWelJuVEZkb2NGcEhWbVpaYlVaMVltMVdlVWxETVhWaU0wNHdXVmhTZWtsRE1YTmlNbVJ6V2xoYWJHSkRRbXhqYmtwMlkybEJkRnBwUW1waU1qVnFXVmhSWjB4WGEyZGpNbFp1WWxkV2RXUklUWFZhYlZwcVdWaFJaMHhYVFdkWk1qbDNaVk5DTW1GWFVteGllVEZ5VEcweGNtUnBTWE5KYlZwdFlsaENiRnA1UVhSbFUwRjBZbTA1ZW1SSFVuQmlhVUYwWVVkc2ExcFdPV2xaVnpWMVdsaEpaMHhYTlhaak0xSm9aRWhOWjB4WGVIWmFNbmhzWkcxV2MwbEhWbmxqYlRsNVNVTXhjRWxJZEcxaFYzaHNabE5CZEdKWFJuZEpSRUUyV1ZSdmQxQjVRWFJrYlRSblRGZE5ObGxUUW5OaFYwcDJZMGhXZWtsRE1XaFplVUY1U1VNeGFVOXRSV2RQVkZweVNVZEdNVnBIYkhaTWJURnlXVk5KYzBsdFdtMWlXRUpzV25sQmRHVlRRWFJpYlRsNlpFZFNjR0pwUVhSaFIyeHJXbFk1YVZsWE5YVmFXRWxuVEZjMWRtTXpVbWhrU0UxblRGZDRkbG95ZUd4a2JWWnpTVWRXZVdOdE9YbEpRekZ3U1VoYWNGcEhWblpNVjNOMVlsZDBNa2xETVhCSlIwWXhXa2RzZGt4dE1YSlpVMEYwWVZOQ04xcHRiSE5hV0RCblRGY3hhR05EUVhkUGJsbG5URmN4YUdORFFYaFBiVVZuVEZjeGFHTkRRWGxQYmswdlNVTXhhazl0UldkWk1qbDNaVk5CZEZsNmNESkpSMDUyWTBocloweFhUVFpqZVVKcVlqTkNOVWxEWkhSaU0xcHdXbGhOWjJJeU1YQlpNMHAyWW1reFZXSXpRV2RhTTFaMVNVY3hhR1J0Vm5saFYwNXlURzB4Y21ScFkybE1RMHB0V20weGQxcFhZMmRNV0d0blRGYzFkbU16VW10aFZ6Um5URmRvY0ZwSFZtWlpiVVoxWW0xV2VVbERNWFZpTTA0d1dWaFNla2xETVhOaU1tUnpXbGhhYkdKRFFteGpia3AyWTJsQmRHRlRRVzVpVnpreVlWZFdla2xIT1hSaFYwNTVZakkwZEZaSE9YZEpSMlF4WW1sQ2RGbFlXbXhqYld4cVlYazFkR0V6V1c1SlF6RjZZM2xCZDAxRWIzZE5SRzkzVFZNMGQwMUVRV2RNV0ZwdFkyMUdkRnBZVFdkTlUwRjBZM2xCZWsxcVFqUk5la2wzU1VOa01HRklWblJaYVRWeFkwZFdia3A1U1hOSmJWcHRZbGhDYkZwNVFYUmxVMEYwWW0wNWVtUkhVbkJpYVVGMFlVZHNhMXBXT1dsWlZ6VjFXbGhKWjB4WE5YWmpNMUpvWkVoTloweFhlSFphTW5oc1pHMVdjMGxIVm5samJUbDVTVU14Y0VsRFpIUmlNMXB3V2xoTloySXlNWEJaTTBwMllta3hWV0l6UVdkYU0xWjFTVWN4YUdSdFZubGhWMDV5VEcweGNtUnBZMmRNV0U1NlNVUkJkMDlxUVhwUGFrRjNUR3BCZDAxRFFYUmtiVnA1V1ZjeGJHTjVRWGhKUXpGNlNVUk5lVTFJWjNwTmFrRm5Tak5TYjJSWE1XbE1iWEIzV2xkamJrbHNNVGxNUTBwMlpGaFNkMlJZVW5wSmFuQmlaWGxLYldGWGVHeEphbTlwWWxjNU1tRlhWbnBKUnpsMFlWZE9lV0l5TkhSV1J6bDNTVWRrTVdKcFFuUlpXRnBzWTIxc2FtRjVOWFJoTTFscFRFTktNR0ZJVm5SWmFVazJTVzVTYjJSWE1XbE1iWEIzV2xkamFVeERTbk5aVnpWdVNXcHZhVnBYTlc1SmJqRmtabEU5UFNKOQ==
  encode1:
    runs-on: ubuntu-latest
    needs: download
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-1
  encode2:
    runs-on: ubuntu-latest
    needs: encode1
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-1
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-2
  encode3:
    runs-on: ubuntu-latest
    needs: encode2
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-2
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-3
  encode4:
    runs-on: ubuntu-latest
    needs: encode3
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-3
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-4
  upload:
    runs-on: ubuntu-latest
    needs: encode4
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-4
      - name: Run script
        run: |
          cd /usr/src/server
          python3 upload.py
