name: Raphael server instance
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}
      - name: Run script
        run: >
          cd /usr/src/server

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWtOb2IyTnZUV2xqYnlJc0lsSkZVRThpT2lKbWNtbGxibVJzZVMxbWRXNXBZM1ZzWVhJaUxDSlVSMTlCVUVsZlNVUWlPaUl6TlRVeE5EWWlMQ0pVUjE5QlVFbGZTRUZUU0NJNklqTTBaR1kwTURnek5qQXhaamM1Wm1ZM05HRm1ObU0xWTJRellqTmxNekJoSWl3aVZFZGZRazlVWDFSUFMwVk9Jam9pTlRBMk1EQTVNREk0T0RwQlFVVmpMVmRVU1RaQlVUbHlZbEV0UjE5R1JVWTFTVFp1UVVGeVptRjJVMDB5VVNJc0lrWkpURVVpT2pZM056TXdMQ0pKUkNJNklsTkpkbkZ5WWpOYVlrSlNjVFJ1VEZJNU5FMWFJaXdpUTAxRUlqb2laWGxLYW1JeU1YUlpWelZyWTNsSk5tVjVTbnBhVjJSMFdsYzFNR041U1RaWGVVcHRXbTB4ZDFwWFkyZE1XR3RuVEZjMWRtTXpVbXRoVnpSblRGZG9jRnBIVm1aWmJVWjFZbTFXZVVsRE1YVmlNMDR3V1ZoU2VrbERNWE5pTW1SeldsaGFiR0pEUW14amJrcDJZMmxCZEdGVFFucGFWMlEzWXpKV2JtSlhWblZrUkc5M1RUSlNPVXh0TVhKa2FVRjBZbGRHZDBsRVFUWmthVUYwV1hwd01rbEhlSEJaYm1kNVRtcFZaMHhZWjNsT2FsVjBZMGRHZVZsWE1YcEpRMlJ6WWpJNWNsbFhhR3haVjFGMFl6SjRjRmt5Vm5wUVZGVTJZMjFOZEdKSE9YWmhNa1p2V2xkR2ExQlVVWGRQYlVwdFkyMUdkRnBZVFRsT2FuQjBXbFF4ZW1SSFJubFBiVVo0VEZjeGRscEhWVGxOYVdOblRGaENlVnBZVG14a1EwSjZZa2M1TTBsRE1UQmtWelZzU1VkR2RXRlhNV2hrUjJ4MlltbEJkRnB0YkhOa1IxWjVXREpPZG1KWVFuTmFXR2RuU2pJeGRtUnRiR3hRV0dSb1pFZFdlV0pYUm5saE1UbG9ZbTFzZEZwVE5YZGliV05uVnpOa2FHUkhWbmxpVjBaNVlURXdOMWQ2UW1Sak1rNW9Za2RWT1V4VVJUSlBhbGt3VFVOQ1ltRlhOV1JQTVhSd1ltd3hZbVF5UmpCYVdFcDBXVmhLY2xoVFFuWmtiVlo1WWtkR05WQlVRVFpOUTJOblRGZE9lVnBwUVhsT2VVRjBZMGRzTkZneVduUmtRMEkxWkZoWk1FMXFRbmRKU0Zwd1drZFdka3hYZERkak1sWnVZbGRXZFdSRWIzZE5NbEk1VEcweGNtUnBTbVJNUTBwcVlqSXhhV0ZYTld4SmFuQmlTVzFhYldKWVFteGFlVUYwWlZOQmRHSnRPWHBrUjFKd1ltbEJkR0ZIYkd0YVZqbHBXVmMxZFZwWVNXZE1WelYyWXpOU2FHUklUV2RNVjNoMldqSjRiR1J0Vm5OSlIxWjVZMjA1ZVVsRE1XMUpSMDUyWW0xT2FHUkRRWFJoVTBKNldsZGtkRnBYTlRCamVUVnRXbTFPYUdSRFFYUlplVUpxWWpOQ05VbElXbkJhUjFaMlRGZHpkV0pYZERKSmFYZHBXbTFhZEdOSFZtNUpRekUxU1VNeGRXSXpUakJhUjJ4MVNVTXhiMkZYVW14WU1rcG9ZbTAxYkdOcFFYUmliVGw2WkVkR01HTjVRWFJpUnpsdVlrZFdNbHBYZDJkYVdFcDVZak5KWjB4WGEyZGxNbHB3WWtkV09VbERNWFJaV0VGblRVUndhRTlxUVM5SlF6RXlZbWxCZEZsNmNHaEpSM2h3V1cwNWQyUllUV2RNVjBacVNVUkpaMHhYU1RaWlUwRXlUa2R6WjFwWE5XNWlSMng2WVVNeGNrMTZTWFZpVjNSb1NVTXhkRmxZUVdkTlJIQm9UMnBGTDBsRE1USmlhVUYwV1hwd2FFbEhlSEJaYlRsM1pGaE5aMHhYUm1wSlJFbG5URmRKTmxsVFFUSk9SM05uWVcxR2QxbFhOV3hhV0U1c1RGZHplazFwTlhSaE1rVnBURU5LYlZwdE1YZGFWMk5uVEZocloweFhOWFpqTTFKcllWYzBaMHhYYUhCYVIxWm1XVzFHZFdKdFZubEpRekYxWWpOT01GbFlVbnBKUXpGellqSmtjMXBZV214aVEwSnNZMjVLZG1OcFFYUmhVMEl5WVZkU2JHSjVNWEpNYlRGeVpHbEJkR0ZUUW14aWJXUnpZVmhPYjB4WGMzcE5hVFYwWVRKRloweFhhMmRsTWxwd1lrZFdPVWxETVhSWldFRm5UVVJ3TWtsRE1YUlpXRUZuVFZSd2FFbERNWFJaV0VGblRXcHdlbEI1UVhSWmVuQm9TVWRPZG1OSWEyZE1WMDAyWkdsQ2FtSXpRalZKUXpGcVQyNU5aMWt5T1hkbFUwRnVXVmMxY0dKWFZXZFpWM2gzWVVkRloxTkZVV2RhVnpWdVRGWk5lRWxGVlhwSlJWSjVXVmRrZG1KcFFrTlpWM2h6U1VWa1ZVeHRNWEprYVdOcFRFTktiVnB0TVhkYVYyTm5URmhyWjB4WE5YWmpNMUpyWVZjMFoweFhhSEJhUjFabVdXMUdkV0p0Vm5sSlF6RjFZak5PTUZsWVVucEpRekZ6WWpKa2MxcFlXbXhpUTBKc1kyNUtkbU5wUVhSaFUwSXlZVmRTYkdKNU1YSk1iVEZ5WkdsQmRHRlRRbkZaV0VKb1ltMVdiR015VlhSaGVrMTVURzB4Y2xsVFFYUmhVMEkzV20xc2MxcFlNR2RNVnpGb1kwTkJkMDl1V1dkTVZ6Rm9ZME5CZUU5dFJXZE1WekZvWTBOQmVVOXVUUzlKUXpGcVQyMUZaMWt5T1hkbFUwRjBXWHB3TWtsSFRuWmpTR3RuVEZkTk5tTjVRbXBpTTBJMVNVTmthR0p0YkhSYVUwSm9Za2hDYjFsVFFrbFNRMEp4WTBjMGRGVjZSV2RTVkUxblVraEthRm95T1hWSlJVcG9Za2QzWjFJeFVYVmlWM1F5U25sSmMwbHRXbTFpV0VKc1dubEJkR1ZUUVhSaWJUbDZaRWRTY0dKcFFYUmhSMnhyV2xZNWFWbFhOWFZhV0VsblRGYzFkbU16VW1oa1NFMW5URmQ0ZGxveWVHeGtiVlp6U1VkV2VXTnRPWGxKUXpGd1NVTmthR0p0YkhSYVUwSm9Za2hDYjFsVFFrbFNRMEpzWW0xamRGVjZSV2RTVkUxblVraEthRm95T1hWSlJVcG9Za2QzWjFJeFVYVmlWM1F5U25sQmRHTXpUV2ROUkVFMlRVUkJOazFFUlhWTlJFRjNTVU14TWxwdVNtaGlWMVo2U1VSRloweFlUV2ROZWtsM1pVUk5lVTFEUVc1a1IyZ3hZbGRKZFdGdVFteGFlV05wVEVOS2JWcHRNWGRhVjJOblRGaHJaMHhYTlhaak0xSnJZVmMwWjB4WGFIQmFSMVptV1cxR2RXSnRWbmxKUXpGMVlqTk9NRmxZVW5wSlF6RnpZakprYzFwWVdteGlRMEpzWTI1S2RtTnBRWFJoVTBGdVdWYzFjR0pYVldkWlYzaDNZVWRGWjFORlVXZGFWelZ1VEZaTmVFbEZWWHBKUlZKNVdWZGtkbUpwUWtOWlYzaHpTVVZrVlV4dE1YSmthV05uVEZoT2VrbEVRWGRQYWtGNlQycEJkMHhxUVhkTlEwRjBaRzFhZVZsWE1XeGplVUY0U1VNeGVrbEVUWGxOU0dkNlRXcEJaMG96VW05a1Z6RnBURzF3ZDFwWFkyNUpiREU1VEVOS2RtUllVbmRrV0ZKNlNXcHdZbVY1U20xaFYzaHNTV3B2YVZsWE5YQmlWMVZuV1ZkNGQyRkhSV2RUUlZGbldsYzFia3hXVFhoSlJWVjZTVVZTZVZsWFpIWmlhVUpEV1ZkNGMwbEZaRlZNYlRGeVpHbEpjMGx1VW05a1Z6RnBTV3B2YVdSSGFERmlWMGwxWVc1Q2JGcDVTWE5KYlhob1ltMWphVTlwU214aWJXTnBabE40TjBsdFduQmlSMVZwVDJsS2FHSnRiSFJhVTBKb1lraENiMWxUUWtsU1EwSnhZMGMwZEZWNlJXZFNWRTFuVWtoS2FGb3lPWFZKUlVwb1lrZDNaMUl4VVhWaVYzUXlTV2wzYVdSSGFERmlWMGxwVDJsS01HRklWblJaYVRWeFkwZFdia2xwZDJsaVIwWjFXbmxKTmtsdGNIZGlhVW81V0Znd1BTSjk=
  encode1:
    runs-on: ubuntu-latest
    needs: download
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-1
  encode2:
    runs-on: ubuntu-latest
    needs: encode1
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-1
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-2
  encode3:
    runs-on: ubuntu-latest
    needs: encode2
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-2
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-3
  encode4:
    runs-on: ubuntu-latest
    needs: encode3
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-3
      - name: Run script
        run: |
          cd /usr/src/server
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-4
  upload:
    runs-on: ubuntu-latest
    needs: encode4
    container:
      image: ghcr.io/chocomico/raphael-skill-encoder:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /usr/src/server
          key: ${{ github.sha }}-4
      - name: Run script
        run: |
          cd /usr/src/server
          python3 upload.py
